# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20161231_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Block',
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),      
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Make')),          
                ('max_price', models.IntegerField(default=4500000)),
                ('min_price', models.IntegerField(default=3500)),
                ('year_interval', models.IntegerField(default=0)),                
            ],
            options={
                'ordering': ('make__alias', 'name'),
            },
        ),
        migrations.CreateModel(
            name='YearFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField(verbose_name='From')),
                ('to_year', models.IntegerField(verbose_name='To')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Model')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='updated',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='prev_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
