# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170318_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_price', models.IntegerField(verbose_name='Low Price')),
                ('avg_price', models.IntegerField(verbose_name='Avg Price')),
                ('high_price', models.IntegerField(verbose_name='High Price')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Model')),
            ],
        ),
    ]
