# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_price_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='low_price',
        ),
        migrations.AddField(
            model_name='price',
            name='uk_avg_price',
            field=models.IntegerField(default=1, verbose_name='UK Average Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='uk_high_price',
            field=models.IntegerField(default=1, verbose_name='UK High Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='uk_low_price',
            field=models.IntegerField(default=1, verbose_name='UK Low Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='usa_avg_price',
            field=models.IntegerField(default=1, verbose_name='USA Average Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='usa_high_price',
            field=models.IntegerField(default=1, verbose_name='USA High Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='usa_low_price',
            field=models.IntegerField(default=1, verbose_name='USA Low Price'),
            preserve_default=False,
        ),
    ]
